<template>
    <div class="col-md-4 mb-3  "><label class="mandatory" for="FechaCirug"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Дата вмешательства</font></font></label> <input type="date" class="form-control" id="FechaCirug" name="FechaCirug" min="" max="" value="" step="" title=""></div>
    <fieldset class="inputwrap">
        <div class="col-md-4 mb-3  readonly"><label for="n_intervencion"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Номер вмешательства.</font></font></label> <input type="number" class="form-control" id="n_intervencion" name="n_intervencion" min="" max="" value="" step="" title="" readonly="true"></div>
        <div class="col-md-4 mb-3   "><label class="mandatory" for="CirugiaCardiacaMayor"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Основная кардиохирургия</font></font></label> <a id="infoCirugiaCardiacaMayor" class="popInfo" href="#" data-content="A efectos del registro, se consideran como procedimientos de <b>Cirugía Cardíaca Mayor</b> a los siguientes procedimientos:<ul><li> 1.Todo procedimiento realizado con circulación extracorpórea (CEC). </li><li>2. Cirugía coronaria sin CEC. </li><li>3. Procedimientos en cardiopatías congénitos sin CEC.</li><li> 4. Pericardiectomías. </li><li>5. Rotura de la pared libre ventricular post-infarto intervenida sin CEC. </li><li>6. Implante de válvulas transcatéter, por cualquier vía de acceso (TAVI).</li><li>7. Cirugía de VM con Técnicas Endovasculares.</li><li>8. Cirugía Aislada de las Arritmias</li>" rel="popover" data-placement="auto" data-html="true" data-original-title="" title=""><span style="color: orange;"><i class="fas fa-info-circle"></i></span></a><select class="form-control" id="CirugiaCardiacaMayor" name="CirugiaCardiacaMayor" title="Для целей регистрации следующие процедуры считаются процедурами <b>Большой кардиохирургии</b>: <ul><li> 1. Любая процедура, выполняемая с использованием экстракорпорального кровообращения (ECC). </li><li>2. Коронарная хирургия без искусственного кровообращения. </li><li>3. Операции при врожденных пороках сердца без искусственного кровообращения.</li><li> 4. Перикардиэктомии. </li><li>5. Постинфарктный разрыв свободной стенки желудочка оперирован без искусственного кровообращения. </li><li>6. Транскатетерная имплантация клапана через любой доступ (TAVI).</li><li>7. Хирургия МК эндоваскулярными методами.</li><li>8. Изолированная хирургия аритмии</li>"><option value="0"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Нет</font></font></option><option value="1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ага</font></font></option></select></div>
    </fieldset>
    <fieldset class="inputwrap">
        <div class="col-md-4 mb-3   "><label class="mandatory" for="PrioridadAgrup"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Приоритет вмешательства</font></font></label> <select class="form-control" id="PrioridadAgrup" name="PrioridadAgrup" title=""><option value="1000"></option><option value="1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Факультативный</font></font></option><option value="2"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Срочный</font></font></option><option value="3"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Чрезвычайный</font></font></option><option value="4"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">На остановке</font></font></option></select></div>
        
    </fieldset>


</template>